use_frameworks!

platform :ios, '13.0'

target 'EasyNavigationBar_Example' do
  pod 'EasyNavigationBar', :path => '../'
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'EasyNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" # for Apple M1
    end
  end
end
