use_frameworks!

platform :ios, '10.0'

target 'EasyNavigationBar_Example' do
  pod 'EasyNavigationBar', :path => '../'
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'EasyNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end
